version: '3'
services:
  db:
    image: postgres
  content-api:
    build: content-api
    ports:
      - "4567:4567"
  rails-app:
    build: rails-app
    command: ./start.sh
    volumes:
      - ./rails-app:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - content-api
    environment:
      DATABASE_URL: postgres://postgres@db/rails-app_development
      CONTENT_API_URL: http://content-api:4567/image_url.json
  worker:
    build: worker
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db/rails-app_development
