apiVersion: batch/v1
kind: Job
metadata:
  name: rails-migrations
spec:
  template:
    spec:
      containers:
      - name: rails-app
        image: "{{ .Values.railsapp.image.repository }}:{{ .Values.railsapp.image.tag }}"
        command: [ "bundle", "exec", "rails", "db:migrate" ]
        env:
          - name: DATABASE_URL
            value: {{ .Values.postgresurl }}
      restartPolicy: OnFailure
  backoffLimit: 4