apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "multi-container-app.name" . }}-railsapp
  labels:
{{ include "multi-container-app.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.railsapp.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "multi-container-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "multi-container-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.railsapp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.railsapp.image.repository }}:{{ .Values.railsapp.image.tag }}"
          imagePullPolicy: {{ .Values.railsapp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.railsapp.containerPort }}
              protocol: TCP
          env:
          - name: DATABASE_URL
            value: {{ .Values.postgresurl }}
          - name: CONTENT_API_URL
            value: {{ .Values.contenapiurl }}
