apiVersion: v1
kind: Service
metadata:
  name: {{ include "multi-container-app.name" . }}-contentapi
  labels:
{{ include "multi-container-app.labels" . | indent 4 }}
spec:
  type: {{ .Values.contentapi.service.type }}
  ports:
    - port: {{ .Values.contentapi.service.port }}
      targetPort: {{ .Values.contentapi.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "multi-container-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
